### ISSUE TITLE
update_autocomplete_input does not update value properly

### ISSUE THREAD

**Issue by RemkoDuursma** [daqana/dqshiny#3]
when using `update_autocomplete_input` to update the `value`, the value shown in the input field is updated, but it is not transmitted to the corresponding `input` slot. 

Example app:

```
library(shiny)
library(dqshiny)

words <- replicate(100, paste(sample(letters,5), collapse=""))

ui <- fluidPage(
  autocomplete_input("x", "vals", options = words),
  actionButton("y", "clear"),
  textOutput("sel")
)

server <- function(input, output, session) {

  output$sel <- renderText({
    input$x
  })
  observeEvent(input$y, {
    update_autocomplete_input(session, "x", value = words[1])
  })
}
shinyApp(ui, server)
```

**Comment by richardkunze** [comment]
Thank you for pointing this out and sorry for my late reply! Issue will be fixed soon.

**Comment by RemkoDuursma** [comment]
Thanks! No worries. I looked to see if I could fix it myself and arrange a pull request, but unfortunately was not able to.

**Comment by richardkunze** [comment]
Should be fixed in the newest version. I will try to publish the next CRAN release in one or two weeks.

**Comment by mercicle** [comment]
@RemkoDuursma was this issue fixed? It still happens to me.. thx!
